// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addedPriceInEvent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedPriceInEvent));
        
        string IMigrationMetadata.Id
        {
            get { return "202103240719177_addedPriceInEvent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
